version: '3.8'

services:
 app:
   build: .
   depends_on:
     - db
   ports:
     - 3000:3000
   networks:
     - labnet
 db:
   image: mongo:latest
   ports:
     - 27017:27017
   networks:
     - labnet
   volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb

volumes:
   mongodb:
   mongodb_config:

networks:
   labnet:
    name: labnet