version: '3.8'

services:
 app:  
   build: .
   labels: 
     - "com.docker.compose.project=bth_demo"
   depends_on:
     - db
   ports:
     - 3000:3000
   networks:
     jenkins:
        aliases:
            - bth_demo
 db:
   image: mongo:latest
   labels: 
     - "com.docker.compose.project=bth_demo"
   ports:
     - 27017:27017
   networks:
     - jenkins
   volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb

volumes:
   mongodb:
   mongodb_config:

networks:
   jenkins:
    name: jenkins