version: '3.8'

services:
 app:
   container_name: BTH_Demo
   image: Anton
   build: .
   depends_on:
     - db
   ports:
     - 3000:3000
   networks:
     jenkins:
        aliases:
            - bth_demo
 db:
   image: mongo:latest
   ports:
     - 27017:27017
   networks:
     - jenkins
   volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb

volumes:
   mongodb:
   mongodb_config:

networks:
   jenkins:
    name: jenkins